import type {
  ActivityCreateRequest,
  ActivityRunContinueRequest,
  ActivityRunResponse,
  ActivityListResponse,
  ActivityPatchRequest,
  ActivityResponse,
  ApiDeleteResponse,
  ApiListQuery,
  ActivityRunListResponse,
  ModelListQuery,
  ModelListResponse,
  ModelResponse,
  PersonaListResponse,
  PersonaListQuery,
  PersonaCreateRequest,
  PersonaPatchRequest,
  PersonaResponse,
  PipelineCreateRequest,
  PipelineListQuery,
  PipelineListResponse,
  PipelinePatchRequest,
  PipelineResponse,
  PipelineRunCreateRequest,
  PipelineRunContinueRequest,
  PipelineRunEventListResponse,
  PipelineRunListQuery,
  PipelineRunListResponse,
  PipelineRunReadinessResponse,
  PipelineRunResponse,
  CatalogProviderResponse,
  CatalogPersonaResponse,
  CatalogSkillResponse,
  LinkedServiceCreateRequest,
  LinkedServicePatchRequest,
  LinkedServiceResponse,
  SkillListResponse,
  SkillListQuery,
  SkillCreateRequest,
  SkillResponse,
  UserResponse,
  UserSettingsRequest,
  ProjectCreateRequest,
  ProjectPatchRequest,
  ProjectResponse,
  WorkerInstanceProjectResponse,
} from '~/types/api'

const resourcePath = (collection: string, id: string) => `/api/v1/${collection}/${encodeURIComponent(id)}`
const projectOptions = (projectId: string) => ({ headers: { 'X-Project-ID': projectId } })

export function useApiClient() {
  return {
    activities: {
      list: (query: ApiListQuery = {}) => $fetch<ActivityListResponse>('/api/v1/activities', { query }),
      get: (id: string) => $fetch<ActivityResponse>(resourcePath('activities', id)),
      create: (body: ActivityCreateRequest) => $fetch<ActivityResponse>('/api/v1/activities', { method: 'POST', body }),
      patch: (id: string, body: ActivityPatchRequest) => $fetch<ActivityResponse>(resourcePath('activities', id), { method: 'PATCH', body }),
      remove: (id: string) => $fetch<ApiDeleteResponse>(resourcePath('activities', id), { method: 'DELETE' }),
      listRuns: (id: string, projectId: string, query: ApiListQuery = {}) => $fetch<ActivityRunListResponse>(`${resourcePath('activities', id)}/runs`, { ...projectOptions(projectId), query }),
      continueRun: (activityId: string, runId: string, projectId: string, body: ActivityRunContinueRequest) => $fetch<ActivityRunResponse>(`${resourcePath('activities', activityId)}/runs/${encodeURIComponent(runId)}/continue`, { ...projectOptions(projectId), method: 'POST', body }),
    },
    pipelines: {
      list: (query: PipelineListQuery = {}) => $fetch<PipelineListResponse>('/api/v1/pipelines', { query }),
      get: (id: string) => $fetch<PipelineResponse>(resourcePath('pipelines', id)),
      create: (body: PipelineCreateRequest) => $fetch<PipelineResponse>('/api/v1/pipelines', { method: 'POST', body }),
      patch: (id: string, body: PipelinePatchRequest) => $fetch<PipelineResponse>(resourcePath('pipelines', id), { method: 'PATCH', body }),
      remove: (id: string) => $fetch<ApiDeleteResponse>(resourcePath('pipelines', id), { method: 'DELETE' }),
      createRun: (id: string, projectId: string, body: PipelineRunCreateRequest) => $fetch<PipelineRunResponse>(`${resourcePath('pipelines', id)}/runs`, { ...projectOptions(projectId), method: 'POST', body }),
      startRun: (pipelineId: string, runId: string, projectId: string) => $fetch<PipelineRunResponse>(`${resourcePath('pipelines', pipelineId)}/runs/${encodeURIComponent(runId)}/start`, { ...projectOptions(projectId), method: 'POST' }),
      continueRun: (pipelineId: string, runId: string, projectId: string, body: PipelineRunContinueRequest) => $fetch<PipelineRunResponse>(`${resourcePath('pipelines', pipelineId)}/runs/${encodeURIComponent(runId)}/continue`, { ...projectOptions(projectId), method: 'POST', body }),
      getRun: (pipelineId: string, runId: string, projectId: string) => $fetch<PipelineRunResponse>(`${resourcePath('pipelines', pipelineId)}/runs/${encodeURIComponent(runId)}`, projectOptions(projectId)),
      getRunReadiness: (pipelineId: string, runId: string, projectId: string) => $fetch<PipelineRunReadinessResponse>(`${resourcePath('pipelines', pipelineId)}/runs/${encodeURIComponent(runId)}/readiness`, projectOptions(projectId)),
      listRunEvents: (pipelineId: string, runId: string, projectId: string, query: ApiListQuery = {}) => $fetch<PipelineRunEventListResponse>(`${resourcePath('pipelines', pipelineId)}/runs/${encodeURIComponent(runId)}/events`, { ...projectOptions(projectId), query }),
    },
    pipelineRuns: {
      list: (projectId: string, query: PipelineRunListQuery = {}) => $fetch<PipelineRunListResponse>('/api/v1/pipeline-runs', { ...projectOptions(projectId), query }),
    },
    personas: {
      list: (query: PersonaListQuery = {}) => $fetch<PersonaListResponse>('/api/v1/personas', { query }),
      get: (id: string) => $fetch<PersonaResponse>(resourcePath('personas', id)),
      create: (body: PersonaCreateRequest) => $fetch<PersonaResponse>('/api/v1/personas', { method: 'POST', body }),
      patch: (id: string, body: PersonaPatchRequest) => $fetch<PersonaResponse>(resourcePath('personas', id), { method: 'PATCH', body }),
      remove: (id: string) => $fetch<ApiDeleteResponse>(resourcePath('personas', id), { method: 'DELETE' }),
    },
    skills: {
      list: (query: SkillListQuery = {}) => $fetch<SkillListResponse>('/api/v1/skills', { query }),
      get: (id: string) => $fetch<SkillResponse>(resourcePath('skills', id)),
      create: (body: SkillCreateRequest) => $fetch<SkillResponse>('/api/v1/skills', { method: 'POST', body }),
      remove: (id: string) => $fetch<ApiDeleteResponse>(resourcePath('skills', id), { method: 'DELETE' }),
    },
    models: {
      list: (query: ModelListQuery = {}) => $fetch<ModelListResponse>('/api/v1/users/me/models', { query }),
      get: (id: string) => $fetch<ModelResponse>(`/api/v1/users/me/models/${encodeURIComponent(id)}`),
    },
    users: {
      registerCurrent: () => $fetch<UserResponse>('/api/v1/users', { method: 'POST' }),
      getCurrent: () => $fetch<UserResponse>('/api/v1/users/me'),
      replaceSettings: (body: UserSettingsRequest) => $fetch<UserResponse>('/api/v1/users/me', { method: 'PATCH', body }),
    },
    catalog: {
      listProviders: (signal?: AbortSignal) => $fetch<CatalogProviderResponse[]>('/api/v1/catalog/providers', { signal }),
      listPersonas: (signal?: AbortSignal) => $fetch<CatalogPersonaResponse[]>('/api/v1/catalog/personas', { signal }),
      listSkills: (signal?: AbortSignal) => $fetch<CatalogSkillResponse[]>('/api/v1/catalog/skills', { signal }),
    },
    projects: {
      list: () => $fetch<ProjectResponse[]>('/api/v1/projects'),
      get: (id: string) => $fetch<ProjectResponse>(resourcePath('projects', id)),
      create: (body: ProjectCreateRequest) => $fetch<ProjectResponse>('/api/v1/projects', { method: 'POST', body }),
      patch: (id: string, body: ProjectPatchRequest) => $fetch<ProjectResponse>(resourcePath('projects', id), { method: 'PATCH', body }),
    },
    workers: {
      list: (projectId: string) => $fetch<WorkerInstanceProjectResponse[]>('/api/v1/workers/instances', projectOptions(projectId)),
    },
    linkedServices: {
      list: (signal?: AbortSignal) => $fetch<LinkedServiceResponse[]>('/api/v1/linked-services', { signal }),
      get: (id: string) => $fetch<LinkedServiceResponse>(resourcePath('linked-services', id)),
      create: (body: LinkedServiceCreateRequest) => $fetch<LinkedServiceResponse>('/api/v1/linked-services', { method: 'POST', body }),
      patch: (id: string, body: LinkedServicePatchRequest) => $fetch<LinkedServiceResponse>(resourcePath('linked-services', id), { method: 'PATCH', body }),
      remove: (id: string) => $fetch<ApiDeleteResponse>(resourcePath('linked-services', id), { method: 'DELETE' }),
    },
  }
}
